"""Roblox Studio Output Exporter.

Converts ForgeCraft GUI JSON specification into:
1. Native Roblox Studio Model (.rbxm XML): can be imported directly into StarterGui via right-click -> "Insert from File..."
2. Standalone Luau Script (.luau): procedural generator script with client event handlers
3. Roblox Studio ZIP Package: bundle containing .rbxm, .luau, and README instructions
"""

import io
import json
import re
import uuid
import zipfile
import xml.etree.ElementTree as ET
from xml.dom import minidom
from typing import Any, Tuple


def _hex_to_rgb(hex_str: str) -> Tuple[float, float, float]:
    """Converts hex color string to 0.0-1.0 float RGB components for Roblox Color3."""
    clean = hex_str.strip().lstrip("#")
    if len(clean) == 3:
        clean = "".join(c * 2 for c in clean)
    if len(clean) != 6:
        return (0.1, 0.1, 0.15)
    try:
        r = int(clean[0:2], 16) / 255.0
        g = int(clean[2:4], 16) / 255.0
        b = int(clean[4:6], 16) / 255.0
        return (round(r, 4), round(g, 4), round(b, 4))
    except ValueError:
        return (0.1, 0.1, 0.15)


def _color3_luau(hex_str: str) -> str:
    """Returns Luau Color3.fromRGB(r, g, b) expression."""
    clean = hex_str.strip().lstrip("#")
    if len(clean) == 3:
        clean = "".join(c * 2 for c in clean)
    if len(clean) != 6:
        return "Color3.fromRGB(24, 24, 36)"
    try:
        r = int(clean[0:2], 16)
        g = int(clean[2:4], 16)
        b = int(clean[4:6], 16)
        return f"Color3.fromRGB({r}, {g}, {b})"
    except ValueError:
        return "Color3.fromRGB(24, 24, 36)"


# -------------------------------------------------------------
# 1. LUAU SCRIPT GENERATOR
# -------------------------------------------------------------

def generate_luau_script(gui_spec: dict[str, Any]) -> str:
    """Generates an optimized, modular Luau script that creates the GUI and sets up interactivity."""
    gui_name = gui_spec.get("name", "ForgeCraftGui")
    lines = [
        "--!strict",
        f"-- Generated by ForgeCraft AI for Roblox Studio",
        f"-- GUI: {gui_name}",
        "",
        'local Players = game:GetService("Players")',
        'local TweenService = game:GetService("TweenService")',
        "",
        'local player = Players.LocalPlayer',
        'local playerGui = player:WaitForChild("PlayerGui")',
        "",
        "-- Create Root ScreenGui",
        f'local screenGui = Instance.new("ScreenGui")',
        f'screenGui.Name = "{gui_name}"',
        'screenGui.ResetOnSpawn = false',
        'screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling',
        'screenGui.Parent = playerGui',
        "",
        "local buttonsToAnimate = {}",
        "local closeButtons = {}",
        "local searchBoxes = {}",
        "local itemGrids = {}",
        "",
    ]

    counter = {"val": 0}

    def render_node(el: dict[str, Any], parent_var: str):
        comp_type = el.get("type", "Frame")
        name = el.get("name", comp_type)
        props = el.get("properties", {})
        counter["val"] += 1
        var_name = f"inst_{counter['val']}"

        lines.append(f'-- [{comp_type}] {name}')
        lines.append(f'local {var_name} = Instance.new("{comp_type}")')
        lines.append(f'{var_name}.Name = "{name}"')

        # Properties
        if "size" in props:
            s = props["size"]
            lines.append(f"{var_name}.Size = UDim2.new({s[0]}, {int(s[1])}, {s[2]}, {int(s[3])})")
        if "position" in props:
            p = props["position"]
            lines.append(f"{var_name}.Position = UDim2.new({p[0]}, {int(p[1])}, {p[2]}, {int(p[3])})")
        if "anchorPoint" in props:
            a = props["anchorPoint"]
            lines.append(f"{var_name}.AnchorPoint = Vector2.new({a[0]}, {a[1]})")
        if "backgroundColor" in props:
            lines.append(f"{var_name}.BackgroundColor3 = {_color3_luau(props['backgroundColor'])}")
        if "backgroundTransparency" in props:
            lines.append(f"{var_name}.BackgroundTransparency = {props['backgroundTransparency']}")
        if "borderSizePixel" in props:
            lines.append(f"{var_name}.BorderSizePixel = {props['borderSizePixel']}")
        else:
            if comp_type in ("Frame", "ScrollingFrame", "TextButton", "TextLabel", "TextBox"):
                lines.append(f"{var_name}.BorderSizePixel = 0")

        if "text" in props:
            safe_text = props["text"].replace('"', '\\"').replace("\n", "\\n")
            lines.append(f'{var_name}.Text = "{safe_text}"')
        if "textColor" in props:
            lines.append(f"{var_name}.TextColor3 = {_color3_luau(props['textColor'])}")
        if "textSize" in props:
            lines.append(f"{var_name}.TextSize = {props['textSize']}")
        if "font" in props:
            lines.append(f'{var_name}.Font = Enum.Font.{props["font"]}')
        if "cornerRadius" in props and comp_type == "UICorner":
            cr = props["cornerRadius"]
            lines.append(f"{var_name}.CornerRadius = UDim.new({cr[0]}, {int(cr[1])})")
        if comp_type == "UIStroke":
            if "strokeColor" in props:
                lines.append(f"{var_name}.Color = {_color3_luau(props['strokeColor'])}")
            if "strokeThickness" in props:
                lines.append(f"{var_name}.Thickness = {props['strokeThickness']}")
        if comp_type == "UIGridLayout":
            if "cellSize" in props:
                cs = props["cellSize"]
                lines.append(f"{var_name}.CellSize = UDim2.new({cs[0]}, {int(cs[1])}, {cs[2]}, {int(cs[3])})")
            if "cellPadding" in props:
                cp = props["cellPadding"]
                lines.append(f"{var_name}.CellPadding = UDim2.new({cp[0]}, {int(cp[1])}, {cp[2]}, {int(cp[3])})")
        if comp_type == "UIListLayout":
            fill_dir = props.get("fillDirection", "Vertical")
            lines.append(f"local fd = Enum.FillDirection.{fill_dir}")
            lines.append(f"{var_name}.FillDirection = fd")
            if "padding" in props:
                pad = props["padding"]
                if isinstance(pad, (list, tuple)) and len(pad) >= 2:
                    lines.append(f"{var_name}.Padding = UDim.new({pad[0]}, {int(pad[1])})")
                else:
                    lines.append(f"{var_name}.Padding = UDim.new(0, {int(pad)})")

        lines.append(f"{var_name}.Parent = {parent_var}")
        lines.append("")

        # Track interactive controls for behavior scripting
        if comp_type in ("TextButton", "ImageButton"):
            if "close" in name.lower():
                lines.append(f"table.insert(closeButtons, {var_name})")
            else:
                lines.append(f"table.insert(buttonsToAnimate, {var_name})")
        elif comp_type == "TextBox" and "search" in name.lower():
            lines.append(f"table.insert(searchBoxes, {var_name})")
        elif comp_type in ("ScrollingFrame", "Frame") and "grid" in name.lower():
            lines.append(f"table.insert(itemGrids, {var_name})")

        # Recurse children
        for child in el.get("children", []):
            if isinstance(child, dict):
                render_node(child, var_name)

    for child in gui_spec.get("children", []):
        if isinstance(child, dict):
            render_node(child, "screenGui")

    # Companion client behavior logic
    lines.extend([
        "-- ============================================",
        "-- CLIENT INTERACTIVITY CONTROLLER",
        "-- ============================================",
        "",
        "-- 1. Button Hover & Click Animations",
        "local tweenInfo = TweenInfo.new(0.15, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)",
        "for _, btn in ipairs(buttonsToAnimate) do",
        "    local originalSize = btn.Size",
        "    local originalColor = btn.BackgroundColor3",
        "    btn.MouseEnter:Connect(function()",
        "        TweenService:Create(btn, tweenInfo, {",
        "            Size = UDim2.new(originalSize.X.Scale * 1.03, originalSize.X.Offset, originalSize.Y.Scale * 1.03, originalSize.Y.Offset)",
        "        }):Play()",
        "    end)",
        "    btn.MouseLeave:Connect(function()",
        "        TweenService:Create(btn, tweenInfo, {",
        "            Size = originalSize",
        "        }):Play()",
        "    end)",
        "    btn.MouseButton1Click:Connect(function()",
        '        print("[ForgeCraft] Clicked button:", btn.Name, btn.Parent and btn.Parent.Name or "")',
        "        -- Custom action hook / Purchase event",
        "    end)",
        "end",
        "",
        "-- 2. Close Buttons Dismissal",
        "for _, closeBtn in ipairs(closeButtons) do",
        "    closeBtn.MouseButton1Click:Connect(function()",
        "        screenGui.Enabled = false",
        '        print("[ForgeCraft] UI Closed")',
        "    end)",
        "end",
        "",
        "-- 3. Live Search Filtering",
        "for _, searchBox in ipairs(searchBoxes) do",
        "    searchBox:GetPropertyChangedSignal('Text'):Connect(function()",
        "        local query = string.lower(searchBox.Text)",
        "        for _, grid in ipairs(itemGrids) do",
        "            for _, item in ipairs(grid:GetChildren()) do",
        "                if item:IsA('Frame') then",
        "                    local itemNameLabel = item:FindFirstChild('ItemName')",
        "                    if itemNameLabel and itemNameLabel:IsA('TextLabel') then",
        "                        local itemName = string.lower(itemNameLabel.Text)",
        "                        item.Visible = query == '' or string.find(itemName, query, 1, true) ~= nil",
        "                    end",
        "                end",
        "            end",
        "        end",
        "    end)",
        "end",
        "",
        f'print("[ForgeCraft] {gui_name} loaded successfully!")',
        "return screenGui",
    ])

    return "\n".join(lines)


# -------------------------------------------------------------
# 2. ROBLOX STUDIO XML MODEL (.RBXM) GENERATOR
# -------------------------------------------------------------

def generate_rbxm_xml(gui_spec: dict[str, Any]) -> bytes:
    """Generates a valid Roblox Studio XML Model (.rbxm) file that can be inserted into StarterGui."""
    root = ET.Element("roblox")
    root.set("xmlns:xmime", "http://www.w3.org/2005/05/xmlmime")
    root.set("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
    root.set("xsi:noNamespaceSchemaLocation", "http://www.roblox.com/roblox.xsd")
    root.set("version", "4")

    referent_id = {"val": 0}

    def next_ref() -> str:
        referent_id["val"] += 1
        return f"RBX_{referent_id['val']}"

    def build_item_xml(el: dict[str, Any], parent_elem: ET.Element):
        comp_type = el.get("type", "Frame")
        name = el.get("name", comp_type)
        props = el.get("properties", {})

        item = ET.SubElement(parent_elem, "Item")
        item.set("class", comp_type)
        item.set("referent", next_ref())

        properties = ET.SubElement(item, "Properties")

        # Name
        prop_name = ET.SubElement(properties, "string")
        prop_name.set("name", "Name")
        prop_name.text = name

        # Size
        if "size" in props:
            s = props["size"]
            udim2 = ET.SubElement(properties, "UDim2")
            udim2.set("name", "Size")
            ET.SubElement(udim2, "XS").text = str(s[0])
            ET.SubElement(udim2, "XO").text = str(int(s[1]))
            ET.SubElement(udim2, "YS").text = str(s[2])
            ET.SubElement(udim2, "YO").text = str(int(s[3]))

        # Position
        if "position" in props:
            p = props["position"]
            udim2 = ET.SubElement(properties, "UDim2")
            udim2.set("name", "Position")
            ET.SubElement(udim2, "XS").text = str(p[0])
            ET.SubElement(udim2, "XO").text = str(int(p[1]))
            ET.SubElement(udim2, "YS").text = str(p[2])
            ET.SubElement(udim2, "YO").text = str(int(p[3]))

        # AnchorPoint
        if "anchorPoint" in props:
            a = props["anchorPoint"]
            vec2 = ET.SubElement(properties, "Vector2")
            vec2.set("name", "AnchorPoint")
            ET.SubElement(vec2, "X").text = str(a[0])
            ET.SubElement(vec2, "Y").text = str(a[1])

        # BackgroundColor3
        if "backgroundColor" in props:
            r, g, b = _hex_to_rgb(props["backgroundColor"])
            c3 = ET.SubElement(properties, "Color3")
            c3.set("name", "BackgroundColor3")
            ET.SubElement(c3, "R").text = str(r)
            ET.SubElement(c3, "G").text = str(g)
            ET.SubElement(c3, "B").text = str(b)

        # BackgroundTransparency
        if "backgroundTransparency" in props:
            bt = ET.SubElement(properties, "float")
            bt.set("name", "BackgroundTransparency")
            bt.text = str(props["backgroundTransparency"])

        # BorderSizePixel
        bsp = ET.SubElement(properties, "int")
        bsp.set("name", "BorderSizePixel")
        bsp.text = str(props.get("borderSizePixel", 0))

        # TextLabel / TextButton / TextBox specific
        if "text" in props:
            txt = ET.SubElement(properties, "string")
            txt.set("name", "Text")
            txt.text = str(props["text"])

        if "textColor" in props:
            r, g, b = _hex_to_rgb(props["textColor"])
            tc = ET.SubElement(properties, "Color3")
            tc.set("name", "TextColor3")
            ET.SubElement(tc, "R").text = str(r)
            ET.SubElement(tc, "G").text = str(g)
            ET.SubElement(tc, "B").text = str(b)

        if "textSize" in props:
            ts = ET.SubElement(properties, "float")
            ts.set("name", "TextSize")
            ts.text = str(props["textSize"])

        # UICorner
        if comp_type == "UICorner" and "cornerRadius" in props:
            cr = props["cornerRadius"]
            udim = ET.SubElement(properties, "UDim")
            udim.set("name", "CornerRadius")
            ET.SubElement(udim, "S").text = str(cr[0])
            ET.SubElement(udim, "O").text = str(int(cr[1]))

        # UIStroke
        if comp_type == "UIStroke":
            if "strokeColor" in props:
                r, g, b = _hex_to_rgb(props["strokeColor"])
                c = ET.SubElement(properties, "Color3")
                c.set("name", "Color")
                ET.SubElement(c, "R").text = str(r)
                ET.SubElement(c, "G").text = str(g)
                ET.SubElement(c, "B").text = str(b)
            if "strokeThickness" in props:
                th = ET.SubElement(properties, "float")
                th.set("name", "Thickness")
                th.text = str(props["strokeThickness"])

        # UIGridLayout
        if comp_type == "UIGridLayout":
            if "cellSize" in props:
                cs = props["cellSize"]
                udim2 = ET.SubElement(properties, "UDim2")
                udim2.set("name", "CellSize")
                ET.SubElement(udim2, "XS").text = str(cs[0])
                ET.SubElement(udim2, "XO").text = str(int(cs[1]))
                ET.SubElement(udim2, "YS").text = str(cs[2])
                ET.SubElement(udim2, "YO").text = str(int(cs[3]))
            if "cellPadding" in props:
                cp = props["cellPadding"]
                udim2 = ET.SubElement(properties, "UDim2")
                udim2.set("name", "CellPadding")
                ET.SubElement(udim2, "XS").text = str(cp[0])
                ET.SubElement(udim2, "XO").text = str(int(cp[1]))
                ET.SubElement(udim2, "YS").text = str(cp[2])
                ET.SubElement(udim2, "YO").text = str(int(cp[3]))

        # Children recursion
        for child in el.get("children", []):
            if isinstance(child, dict):
                build_item_xml(child, item)

    # Build ScreenGui root
    root_item = ET.SubElement(root, "Item")
    root_item.set("class", "ScreenGui")
    root_item.set("referent", next_ref())

    root_props = ET.SubElement(root_item, "Properties")
    p_name = ET.SubElement(root_props, "string")
    p_name.set("name", "Name")
    p_name.text = gui_spec.get("name", "ForgeCraftGui")

    p_reset = ET.SubElement(root_props, "bool")
    p_reset.set("name", "ResetOnSpawn")
    p_reset.text = "false"

    for child in gui_spec.get("children", []):
        if isinstance(child, dict):
            build_item_xml(child, root_item)

    # Attach companion LocalScript to the ScreenGui
    local_script = ET.SubElement(root_item, "Item")
    local_script.set("class", "LocalScript")
    local_script.set("referent", next_ref())
    ls_props = ET.SubElement(local_script, "Properties")
    ls_name = ET.SubElement(ls_props, "string")
    ls_name.set("name", "Name")
    ls_name.text = "GuiController"

    ls_code = ET.SubElement(ls_props, "ProtectedString")
    ls_code.set("name", "Source")
    ls_code.text = """--!strict
-- Auto-generated Interaction Controller
local TweenService = game:GetService("TweenService")
local screenGui = script.Parent

-- Close buttons dismissal
for _, desc in ipairs(screenGui:GetDescendants()) do
    if (desc:IsA("TextButton") or desc:IsA("ImageButton")) and string.find(string.lower(desc.Name), "close") then
        desc.MouseButton1Click:Connect(function()
            screenGui.Enabled = false
        end)
    end
end
"""

    rough_string = ET.tostring(root, "utf-8")
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ", encoding="utf-8")


# -------------------------------------------------------------
# 3. ZIP PACKAGE BUILDER
# -------------------------------------------------------------

def generate_roblox_zip_package(gui_spec: dict[str, Any]) -> bytes:
    """Creates a complete downloadable ZIP containing .rbxm, .luau, and import README."""
    gui_name = gui_spec.get("name", "ForgeCraftGui")
    clean_name = re.sub(r"[^a-zA-Z0-9_-]", "_", gui_name)

    rbxm_bytes = generate_rbxm_xml(gui_spec)
    luau_code = generate_luau_script(gui_spec)

    readme_content = f"""# ForgeCraft Roblox GUI Package: {gui_name}

This package contains production-ready Roblox Studio UI assets generated by ForgeCraft AI.

## Quick Installation Guide (Roblox Studio)

### Method 1: Instant Drag & Drop (Recommended)
1. Open your Roblox game in **Roblox Studio**.
2. Open the **Explorer** window (`View` -> `Explorer`).
3. Find **StarterGui**.
4. Right-click **StarterGui** -> **Insert from File...**
5. Select `{clean_name}.rbxm` from this package.
6. Done! Your GUI is loaded with complete hierarchy, layout, styling, and controller script.

---

### Method 2: Scripted Creation via Command Bar or Script
1. Open the Roblox Studio **Command Bar** (`View` -> `Command Bar`).
2. Paste or require the contents of `Create_{clean_name}.luau`.
3. Press **Enter** to instantly build the GUI hierarchy into `PlayerGui`.

---

## Included Files
- `{clean_name}.rbxm`: Native Roblox Studio Model file containing the complete ScreenGui.
- `Create_{clean_name}.luau`: Self-contained Luau constructor script.
- `GuiSpec.json`: The source-of-truth ForgeCraft JSON specification.
"""

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{clean_name}/{clean_name}.rbxm", rbxm_bytes)
        zf.writestr(f"{clean_name}/Create_{clean_name}.luau", luau_code)
        zf.writestr(f"{clean_name}/GuiSpec.json", json.dumps(gui_spec, indent=2))
        zf.writestr(f"{clean_name}/README.md", readme_content)

    buffer.seek(0)
    return buffer.getvalue()
